/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommonOutput } from "./CommonOutput"
import { EAgreementBatchResponse } from "./EAgreementBatchResponse"
import { FaultType } from "./FaultType"
import { MycarenetError } from "./MycarenetError"

import { decodeBase64 } from "./ModelHelper"

export class EAgreementMessage {
  constructor(json: JSON | any) {
    Object.assign(this as EAgreementMessage, json)
  }

  appliesTo?: string
  commonOutput?: CommonOutput
  complete?: boolean
  eagreementResponse?: Array<EAgreementBatchResponse>
  errors?: Array<MycarenetError>
  genericErrors?: Array<FaultType>
  io?: string
  reference?: string
  valueHash?: string
}
