/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Assertion } from "./Assertion"
import { FaultType } from "./FaultType"
import { MdaStatus } from "./MdaStatus"
import { MycarenetError } from "./MycarenetError"
import { XMLGregorianCalendar } from "./XMLGregorianCalendar"

import { decodeBase64 } from "./ModelHelper"

export class EAgreementBatchResponse {
  constructor(json: JSON | any) {
    Object.assign(this as EAgreementBatchResponse, json)
  }

  assertions?: Array<Assertion>
  errors?: Array<FaultType>
  inResponseTo?: string
  issueInstant?: XMLGregorianCalendar
  issuer?: string
  myCarenetErrors?: Array<MycarenetError>
  responseId?: string
  status?: MdaStatus
  value?: string
}
