/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EAgreementMessage } from "./EAgreementMessage"
import { FaultType } from "./FaultType"
import { MycarenetConversation } from "./MycarenetConversation"

import { decodeBase64 } from "./ModelHelper"

export class EAgreementList {
  constructor(json: JSON | any) {
    Object.assign(this as EAgreementList, json)
  }

  date?: Date
  eagreementMessageList?: Array<EAgreementMessage>
  genericErrors?: Array<FaultType>
  mycarenetConversation?: MycarenetConversation
}
